language: python
python:
  - "2.7"
  - "3.3"
# command to install dependencies
install:
  - pip install nose coverage argparse python-dateutil docutils
# command to run tests
script:
  - nosetests -s --tests test
notifications:
  email: false
